### ISSUE TITLE
[TOPS Pvp & Pve] Azerothcore and TrinityCore

### ISSUE THREAD

**Issue by ghost** [Helias/TC-PvEstats#1]
Hi @Helias
Please creat new project and help to update(tops pvp/pve) web.
I think it's very good and very popular!

INFORMATIONS:
The project web tops pvp and pve is for azerothcore and trinitycore last,rev 3.3.5

Ready items: (worked) 
top player Achievements
top killers
top arena points
top honor points
top arena teams
top player play time

**Comment by Helias** [comment]
Thanks for this suggestion, If I'll do new projects about this or just improve this project adding this feature I'll add a reference to this issue.

**Comment by ghost** [comment]
Dear , this page is worked for tops of server ! Az/Tc

**Comment by Helias** [comment]
I see, I have no time in this period, if I can I'll update you.

**Comment by ghost** [comment]
Need items: (upgrade)
 is ready but don't work listed to ranked!

**Comment by Helias** [comment]
Anyway, create a open source repository on GitHub to get easily help from a third contributor
